[appearance]
colorscheme = 'eldritch'
syntax = 'on'
# syntax = 'sync minlines=256'

[appearance.set]
cursorline = ''
lazyredraw = ''
background = 'dark'
guicursor = 'n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor'
fillchars = "vert:┃"
updatetime=100
nocursorcolumn = ''
nocursorline = ''
synmaxcol=300

# [appearance.set.termguicolors]
# if = 'has("termguicolors")'

[folding]

[folding.set]
foldlevel = '2'
foldmethod = 'marker'
