[appearance]
colorscheme = 'eldritch'
syntax = 'on'
# syntax = 'sync minlines=256'

[appearance.set]
cursorline = ''
lazyredraw = ''
background = 'dark'
guicursor = 'n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor'
fillchars = "vert:┃"
updatetime=100
nocursorcolumn = ''
nocursorline = ''
synmaxcol=300

# [appearance.set.termguicolors]
# if = 'has("termguicolors")'

[folding]

[folding.set]
foldlevel = '2'
foldmethod = 'marker'
foldmarker= '#--,--'

[search]
[search.set]
# search as characters are typed
incsearch = ''
# highlight matches
hlsearch = ''
# ignore case of searches
ignorecase = ''
# default to global search
gdefault = ''
# ignore ignore case if uppercase letters
smartcase = ''
# Searches wrap around end of file
wrapscan = ''

[indent]
filetype ='indent on' # load filetype-specific indents
[indent.set]
expandtab=''                         # tabs are spaces
softtabstop=2                     # number of columns in insert mode
smartindent=''                       # indent files smartly
ts=2
sw=2
et=''
# let g:indent_guides_enable_on_vim_startup = 1
# let g:indent_guides_start_level = 2
# let g:indent_guides_guide_size = 1
# let g:indent_guides_auto_colors = 1
# let g:indent_guides_color_change_percent = 5
# let g:indent_guides_exclude_filetypes = ['help', 'netrw']

[undo]
[undo.set]
undofile=''                                  # persistent undo
backupdir='~/.config/nvim/backups'          # use global backup directory
directory='~/.config/nvim/swaps'            # use global swaps directory
undodir='~/.config/nvim/undo'               # use global undo directory
