[[plugins]]
repo='onsails/lspkind-nvim'
hook_add='''
lua <<EOF
require('lspkind').init({
  -- with_text = true,
  -- symbol_map = {
  --   Text = '',
  --   Method = 'ƒ',
  --   Function = '',
  --   Constructor = '',
  --   Variable = '',
  --   Class = '',
  --   Interface = 'ﰮ',
  --   Module = '',
  --   Property = '',
  --   Unit = '',
  --   Value = '',
  --   Enum = '了',
  --   Keyword = '',
  --   Snippet = '﬌',
  --   Color = '',
  --   File = '',
  --   Folder = '',
  --   EnumMember = '',
  --   Constant = '',
  --   Struct = ''
    -- },
})
EOF
'''

[[plugins]]
repo='https://git.sr.ht/~wuz/scuttle.vim'
hook_add='''
command! -nargs=+ Scuttle call scuttle#add(<q-args>, expand('<sfile>'), expand('<slnum>'))
command! ScuttleList call scuttle#list()

Scuttle <Tab><Tab> Show Scuttle List
nnoremap <Tab><Tab> :ScuttleList<CR>

Scuttle <Leader>Enter (basics) insert new line in visual mode
nnoremap <Leader><CR> o<esc>
Scuttle <Leader>x (basics) unhighlight everything
nnoremap <Leader>x :noh<CR>

Scuttle <Leader>b (denite) show buffer list
nmap <Leader>b :Denite buffer<CR>
Scuttle <Leader>t (denite) show project dir
nmap <Leader>t :DeniteProjectDir file/rec<CR>
Scuttle <Leader>g (denite) grep with denit
nnoremap <Leader>g :<C-u>Denite grep:. -no-empty<CR>


Scuttle n (movement) keep search term centered while navigating forward
nnoremap n nzzzv

Scuttle N (movement) keep search term centered while navigating backward
nnoremap N Nzzzv 

Scuttle <Leader>a (searching/replace) Open ripgrep search
nnoremap <Leader>a :Rg<CR>
Scuttle <Leader>G (searching/replace) Ripgrep search for word under cursor
nmap <expr> <leader>G ':Rg \b'.expand('<cword>').'\b<cr>'

" Scuttle <Leader>f (searching/replace) Edit quickfix buffer
" map <Leader>f :EnMasse<CR>

Scuttle <Leader>y (copy/paste) Yank to system clipboard
vmap <Leader>y "+y 
Scuttle <Leader>d (copy/paste) Delete to system clipboard
vmap <Leader>d "+d 
Scuttle <Leader>p (copy/paste) Paste from system clipboard (below)
nmap <Leader>p "+p 
vmap <Leader>p "+p

Scuttle <Leader>P (copy/paste) Paste from system clipboard (above)
nmap <Leader>P "+P
vmap <Leader>P "+P

Scuttle <Leader>r (searching/replace) Replace globally
vmap <Leader>r "hy:%s/<C-r>h//gc<left><left><left>

Scuttle <Leader>ls (sessions) Load last vim session
nmap <Leader>ls <Plug>(load-session)

Scuttle <Leader>ms (sessions) Make and save new vim session
nmap <Leader>ms <Plug>(make-session)

Scuttle <Leader><Tab> (wiki) Open VimwikiIndex
nnoremap <Leader><Tab> :VimwikiIndex<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

'''


[[plugins]]
repo="lambdalisue/gina.vim"
hook_source='''
command! -bang -nargs=? -complete=dir Owners ! git blame --line-porcelain % | sed -n 's/^author //p' | sort | uniq -c | sort -rn
'''

[[plugins]]
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo='mhinz/vim-signify'

[[plugins]]
repo='tpope/vim-abolish'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'xolox/vim-reload'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'christoomey/vim-conflicted'

[[plugins]]
repo = 'matze/vim-move'
