
[[plugins]]
repo='dstein64/vim-startuptime'
on_cmd=['StartupTime']


[[plugins]]
repo='tpope/vim-rails'
on_ft='ruby'

[[plugins]]
repo='jocap/rich.vim'
on_ft='markdown'

[[plugins]]
repo='neoclide/jsonc.vim'
on_ft=['json', 'jsonc']
hook_add='''
augroup jsonc_ft
  au!
  autocmd BufNewFile,BufRead *.json set syntax=jsonc
augroup END
'''

[[plugins]]
repo='AndrewRadev/tagalong.vim'
on_ft=['html', 'xml', 'jsx', 'eruby', 'ejs', 'eco', 'php', 'htmldjango', 'javascriptreact', 'typescriptreact']

[[plugins]]
repo='captbaritone/better-indent-support-for-php-with-html'
on_ft='php'


[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
let g:echodoc#type = 'virtual'
call echodoc#enable()
'''

[[plugins]]
repo = 'ncm2/float-preview.nvim'
on_source = 'deoplete.nvim'
if = 'has("nvim")'
hook_source = '''
let g:float_preview#docked = 0
let g:float_preview#max_width = 60
let g:float_preview#max_height = 20
'''

[[plugins]]

[[plugins]]
repo = 'Olical/vim-enmasse'
on_cmd=['EnMasse']

[[plugins]]
repo = 'chrisbra/NrrwRgn'
on_cmd=['NR','NW','WR','NRV ','NUD','NRP','NRM','NRS','NRN','NRL']

[[plugins]]
repo = 'junegunn/goyo.vim'
on_cmd=['Goyo']

